using System.Diagnostics;
using Conduit.Core.Events;
using Conduit.Core.Interfaces;
using Conduit.EventBus;
using Conduit.Extractors;
using Conduit.Handlers;
using Conduit.Loaders;
using Conduit.Pipeline;
using Conduit.Transformers;

Console.OutputEncoding = System.Text.Encoding.UTF8;

// ─────────────────────────────────────────────────────────────────────────────
// CLI flags:  --batch    run only the batch pipeline
//             --stream   run only the streaming pipeline
//             (default)  run both
// ─────────────────────────────────────────────────────────────────────────────
var runBatch  = args.Contains("--batch")  || !args.Contains("--stream");
var runStream = args.Contains("--stream") || !args.Contains("--batch");

// ─────────────────────────────────────────────────────────────────────────────
// Metric helpers
// ─────────────────────────────────────────────────────────────────────────────
static (long workingSet, long gcBytes, TimeSpan cpuTime) Snapshot()
{
    GC.Collect(2, GCCollectionMode.Aggressive, blocking: true, compacting: true);
    var proc = Process.GetCurrentProcess();
    proc.Refresh();
    return (proc.WorkingSet64, GC.GetTotalMemory(false), proc.TotalProcessorTime);
}

static void PrintMetrics(
    (long workingSet, long gcBytes, TimeSpan cpuTime) before,
    (long workingSet, long gcBytes, TimeSpan cpuTime) after,
    TimeSpan wallClock)
{
    var wsDelta = (after.workingSet - before.workingSet) / 1_048_576.0;
    var gcDelta = (after.gcBytes    - before.gcBytes)    / 1_048_576.0;
    var cpuMs   = (after.cpuTime    - before.cpuTime).TotalMilliseconds;
    Console.WriteLine($"    Wall-clock : {wallClock.TotalMilliseconds,8:F0} ms");
    Console.WriteLine($"    CPU time   : {cpuMs,8:F0} ms");
    Console.WriteLine($"    Working Δ  : {wsDelta,8:+0.0;-0.0} MB");
    Console.WriteLine($"    GC heap Δ  : {gcDelta,8:+0.0;-0.0} MB");
}

// ─────────────────────────────────────────────────────────────────────────────
// Shared event bus — ConsoleLoggingHandler logs lifecycle events
// ─────────────────────────────────────────────────────────────────────────────
var bus = new InMemoryEventBus();
var logger = new ConsoleLoggingHandler();
bus.Subscribe((IEventHandler<PipelineStartedEvent>)logger);
bus.Subscribe((IEventHandler<StageCompletedEvent>)logger);
bus.Subscribe((IEventHandler<PipelineCompletedEvent>)logger);
bus.Subscribe((IEventHandler<PipelineFailedEvent>)logger);

// ─────────────────────────────────────────────────────────────────────────────
// Benchmark loop — reads from CSV files generated by scripts/generate_csv.py
// ─────────────────────────────────────────────────────────────────────────────
var configs = new[]
{
    // (label: "1M",   file: "data/employees_1m.csv"),
    // (label: "10M",  file: "data/employees_10m.csv"),
    // (label: "50M",  file: "data/employees_50m.csv"),
    (label: "100M", file: "data/employees_100m.csv"),
};

foreach (var (label, file) in configs)
{
    if (!File.Exists(file))
    {
        Console.WriteLine($"\n  [SKIP] {file} not found — run scripts/generate_csv.py first.");
        continue;
    }

    Console.WriteLine($"\n╔══════════════════════════════════════════════════════╗");
    Console.WriteLine($"║  {label} rows  ({file})                    ");
    Console.WriteLine($"╚══════════════════════════════════════════════════════╝");

    // ── Batch ────────────────────────────────────────────────────────────────
    if (runBatch)
    {
        Console.WriteLine($"\n  ▶ Batch  (CsvExtractor — full file loaded into memory)\n");

        var batchLoader = new InMemoryLoader<string>();

        var batchPipeline = EtlPipelineBuilder
            .WithExtractor(new CsvExtractor(file))
            .WithName($"Batch {label}")
            .WithEventBus(bus)
            .WithTransformer(new DelegateTransformer<Dictionary<string, string>, string>(r =>
                $"{r["Id"]}|{r["Name"]}|{r["Department"]}|{r["Salary"]}"))
            .WithLoader(batchLoader);

        var bBefore = Snapshot();
        var bSw     = Stopwatch.StartNew();
        var bResult = await batchPipeline.RunAsync();
        bSw.Stop();
        var bAfter  = Snapshot();

        Console.WriteLine($"\n  Result: {bResult}");
        PrintMetrics(bBefore, bAfter, bSw.Elapsed);
        Console.WriteLine($"    Processed  : {batchLoader.LoadedRecords.Count:N0}");
    }

    // ── Streaming ────────────────────────────────────────────────────────────
    if (runStream)
    {
        Console.WriteLine($"\n  ▶ Streaming  (CsvStreamingExtractor — one row at a time)\n");

        var streamProcessed = 0;

        var streamingPipeline = StreamingEtlPipelineBuilder
            .WithExtractor(new CsvStreamingExtractor(file))
            .WithName($"Streaming {label}")
            .WithEventBus(bus)
            .WithTransformCallback(r =>
                $"{r["Id"]}|{r["Name"]}|{r["Department"]}|{r["Salary"]}")
            .WithLoadCallback((string _, CancellationToken _) =>
            {
                Interlocked.Increment(ref streamProcessed);
                return Task.CompletedTask;
            });

        var sBefore = Snapshot();
        var sSw     = Stopwatch.StartNew();
        var sResult = await streamingPipeline.RunAsync();
        sSw.Stop();
        var sAfter  = Snapshot();

        Console.WriteLine($"\n  Result: {sResult}");
        PrintMetrics(sBefore, sAfter, sSw.Elapsed);
        Console.WriteLine($"    Processed  : {streamProcessed:N0}");
    }
}

